### ISSUE TITLE
Dependencies with scope "test" are included in the license check

### ISSUE THREAD

**Issue by Sandared** [carlomorelli/licensescan-maven-plugin#22]
Hi @carlomorelli ,

first off: thanks for this plugin. It really is very helpful :)
However, I currently have the problem, that the plugin includes my test dependencies in its check, which (according to your documentation) is not what is intended.

Maybe one could explicitly remove those dependencies when fetching all artifacts to make sure that test dependencies are not included?

WDYT?

Kind regards,
Thomas

**Comment by carlomorelli** [comment]
Hi,
could you please attach as much info as you can. Which java+mvn version you're on, any output of mvn stack trace of errors would be also very helpful. 

It's difficult to say what you are experiencing without more data. In the code the plugin just uses a predefined framework primitive scope called "RUNTIME+COMPILE". If this is malfunctioning, I am afraid there is some weird combination of env conditions.

**Comment by carlomorelli** [comment]
No replies in 13 days, so I'm closing this.
