### ISSUE TITLE
Feature Request: Skip Transitive Dependencies

### ISSUE THREAD

**Issue by PascalTurbo** [carlomorelli/licensescan-maven-plugin#24]
It would be great to add a flag to skip transitiv dependency analysis and just analyze the base dependencies.

**Comment by carlomorelli** [comment]
Can you explain more in depth what use case would this cover? Without further detail, I don't think this option would have applications.

**Comment by PascalTurbo** [comment]
No problem. For our compliance it's ok to only check the base dependencies for "toxic" licenses. We don't need to analyze, if our dependencies are using dependencies with these licenses.

**Comment by carlomorelli** [comment]
I honestly think you do, and I suggest to double check with your consultant on this matter. If you bring a dependency at compile time, doesn't matter if it is direct or indirect: **you are linking towards it**.

For this reason, I'll close the issue.
