### ISSUE TITLE
Add whitelist parameters

### ISSUE THREAD

**Issue by carlomorelli** [carlomorelli/licensescan-maven-plugin#3]

**Comment by ryber** [comment]
Curious what you mean by this? Do you mean so say "ONLY support these licenses" OR "These are dependencies that would normally fail but we are OK with anyway".

**Comment by carlomorelli** [comment]
In light of your last Regex addition, I would do it this way (as it was suggested to me in the past by a discussion around the web):

Enlarge the design of the Mojo configuration:

`<blacklistedLicenses/>` - this list is for the licenses that are unwanted, e.g. GNU GPL, Affero
`<whitelistedLicenses/>` - a similar list for licenses that we deem good (permissive), eg. MIT, Apache, LGPL, etc..
`<whitelistedOverrule/>` - a boolean switch that tells us if whitelisted licenses ovverrule the blacklisted ones or viceversa. 

Example of application:
say that we have a dually licensed JAR: GPL and LGPL (for the sake of example -- this is a very common pairing btw).
Say that GPL is in out blacklist and LGPL is in our whitelist. What to do?
If the boolean `<whitelistOverrule>` is true, the plugin will allow the build to pass.
If the boolean `<whitelistOverrule>` it false, the plugin will make the build fail.

I believe a sane default for` whitelistOverrule` is the permissive one (set to true).

Makes sense?

**Comment by carlomorelli** [comment]
Another application will be that if you have regex strings in Blacklist (e.g. "`regex:.* GPL .`*"), we can use the Whitelist so we can manage special cases that otherwise would be thrown away (e.g. "`Affero GPL`"), of course by setting whitelistOverule=true

**Comment by carlomorelli** [comment]
closing this issue. the project has moved in a different direction eventually, so it is basically outdated.
